//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 按照更快的频率(由 5分钟 提高到 30秒 )记录计算机的中央处理器散热风扇转速，用以详细的监察计算机处理器风扇是否发生过速状况 的本地化字符串。
        /// </summary>
        internal static string CPU_allFanSpeed_Description {
            get {
                return ResourceManager.GetString("CPU_allFanSpeed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按照更快的频率(由 5分钟 提高到 30秒 )记录计算机的中央处理器温度，用以详细的监察计算机处理器是否发生过温状况 的本地化字符串。
        /// </summary>
        internal static string CPU_AllTemp_Description {
            get {
                return ResourceManager.GetString("CPU_AllTemp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按照更快的频率(由 5分钟 提高到 30秒 )记录计算机的中央处理器总利用率，用以详细评估各时间段内处理器利用率及其散热功效。此选项建议和记录温度、风扇风速一并使用。 的本地化字符串。
        /// </summary>
        internal static string CPU_details_Description {
            get {
                return ResourceManager.GetString("CPU_details_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许对中央处理器进行压力测试，将采用循环数学问题计算方案。在此期间，计算机可能因为应用程序的大规模运算产生卡顿。此测试将持续 6 小时 的本地化字符串。
        /// </summary>
        internal static string CPU_Enable_Description {
            get {
                return ResourceManager.GetString("CPU_Enable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将在此处显示具体项目的描述，将鼠标悬停在任意控件上查看详情... 的本地化字符串。
        /// </summary>
        internal static string default_Description {
            get {
                return ResourceManager.GetString("default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用组件chkdsk对计算机的磁盘进行坏道检查。此检查视磁盘大小将执行一段时间。在此时间内，磁盘将被大规模读取和占用，也可能造成无法恢复的文件丢失。请在执行操作之前进行适当的备份。将回传详细chkdsk日志供服务器识别和认证。 的本地化字符串。
        /// </summary>
        internal static string Disk_chkdsk_Description {
            get {
                return ResourceManager.GetString("Disk_chkdsk_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现任何错误，包括软件报错、硬件错误、通信错误、无响应等情况时立即停止操作。此选项能够防止计算机在测试时陷入无法处理的问题，包括但不限于BSoD、硬件损毁等。 的本地化字符串。
        /// </summary>
        internal static string Error_Stop_Description {
            get {
                return ResourceManager.GetString("Error_Stop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许对计算机内部存储器进行存取实验，将创建多个子进程/线程对内存进行分别大规模分配请求和占用，并持续足够长时间( 6 小时)。测试期间可能因为计算机内存大量被占用导致计算机部分程序运行失常，故建议在执行此测试之前关闭所有其他应用程序。 的本地化字符串。
        /// </summary>
        internal static string Mem_Enable_Description {
            get {
                return ResourceManager.GetString("Mem_Enable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果在存取期间出现程序异常，将试图获取异常的地址。此功能尚未完善。 的本地化字符串。
        /// </summary>
        internal static string Mem_ErrorLocation_Description {
            get {
                return ResourceManager.GetString("Mem_ErrorLocation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行服务器通信测试。 的本地化字符串。
        /// </summary>
        internal static string Net_CommCheck_Description {
            get {
                return ResourceManager.GetString("Net_CommCheck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行网络测试。由于与服务器通信总是建立，因此此测试不可取消。 的本地化字符串。
        /// </summary>
        internal static string Net_Enable_Description {
            get {
                return ResourceManager.GetString("Net_Enable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将对计算机各适配器的MAC地址进行合规性测试。合规性测试采用IEEE 802.1a规范。请访问https://1.ieee802.org/security/802-1ae/ 获取更多信息 的本地化字符串。
        /// </summary>
        internal static string Net_MAC_Description {
            get {
                return ResourceManager.GetString("Net_MAC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行简易互联网访问测试，将检查包括DNS、TCP/IP在内的一系列协议的工作正常与否。将尝试向指定网站 (设定为哈尔滨工程大学官网/218.7.43.8) 发送ICMP握手通信数据包。 的本地化字符串。
        /// </summary>
        internal static string Net_web_Description {
            get {
                return ResourceManager.GetString("Net_web_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验所有可以获取到的配置信息。此信息将作为附件附加在日志后 的本地化字符串。
        /// </summary>
        internal static string Other_AllInfo_Description {
            get {
                return ResourceManager.GetString("Other_AllInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验自定义的配置 的本地化字符串。
        /// </summary>
        internal static string Other_Preset_Description {
            get {
                return ResourceManager.GetString("Other_Preset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传递本机时间而不是互联网时间。在传递之前将传递一些测试封包以测试网络延迟均值。此延迟将被加和在传递的RTC上。 的本地化字符串。
        /// </summary>
        internal static string Other_RTCLocal_Description {
            get {
                return ResourceManager.GetString("Other_RTCLocal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将试图向音频输入输出设备输出一段音频(\b)，此音频简要描述为: 计算机的响铃声 的本地化字符串。
        /// </summary>
        internal static string Outlet_audioPlay_Description {
            get {
                return ResourceManager.GetString("Outlet_audioPlay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将试图先各COM端口发送测试数据(0x80AE6045)。请注意此数据可能成为某些连接在COM端口的设备的指令码。您可能需要额外设备获取这些数据，以验证COM端口的完整性。由于回环限制，暂不支持回环测试。 的本地化字符串。
        /// </summary>
        internal static string Outlet_COM_Description {
            get {
                return ResourceManager.GetString("Outlet_COM_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对各外设组件，包括通用串行总线控制器(USB)、端口(COM)、音频输入输出设备进行测试。 的本地化字符串。
        /// </summary>
        internal static string Outlet_Description {
            get {
                return ResourceManager.GetString("Outlet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将试图向接入计算机的所有USB设备写入一段数据，为保证测试安全性，您可能需要插入USB存储器。插入存储器时，将试图向存储器写入文件并擦除。文件内容为 Harbin Engineering University , 写入到根目录下test.bin中 的本地化字符串。
        /// </summary>
        internal static string Outlet_USB_Description {
            get {
                return ResourceManager.GetString("Outlet_USB_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将试图更改音频输入输出设备的音量，每隔10音量播放一次音频，以此调查计算机音频输入输出设备是否可以调控音量。 的本地化字符串。
        /// </summary>
        internal static string Outlet_VolAuto_Description {
            get {
                return ResourceManager.GetString("Outlet_VolAuto_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消自动调整音频，试图将音量设置为最大。 的本地化字符串。
        /// </summary>
        internal static string Outlet_VolMax_Description {
            get {
                return ResourceManager.GetString("Outlet_VolMax_Description", resourceCulture);
            }
        }
    }
}
